UPDATE DM.DM_ACCOUNT_TURNOVER_F
SET
	CREDIT_AMOUNT = 0
WHERE
	CREDIT_AMOUNT IS NULL;

UPDATE DM.DM_ACCOUNT_TURNOVER_F
SET
	CREDIT_AMOUNT_RUB = 0
WHERE
	CREDIT_AMOUNT_RUB IS NULL;

UPDATE DM.DM_ACCOUNT_TURNOVER_F
SET
	DEBET_AMOUNT = 0
WHERE
	DEBET_AMOUNT IS NULL;

UPDATE DM.DM_ACCOUNT_TURNOVER_F
SET
	DEBET_AMOUNT_RUB = 0
WHERE
	DEBET_AMOUNT_RUB IS NULL;